### PR TITLE
Standardize package

### PR DESCRIPTION
**Pull request by petricm**
BEGINRELEASENOTES
- Make LCFIPlus compliant to standard iLCSoft package 

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
It is really more a question for @gaede if LCFIPlus is now taken from here or its own project.

**Comment by petricm** [comment]
Coverity is up and running

**Comment by petricm** [comment]
@gaede given that you used this repo for the [last release](https://github.com/iLCSoft/iLCInstall/blob/v01-19-03/releases/v01-19/release-ilcsoft.cfg#L172) is this now the main repo?

**Comment by gaede** [comment]
we still have to discuss this with the authors...

**Comment by gaede** [comment]
The leading repository is now back to https://github.com/lcfiplus/LCFIPlus.

**Pull request closed without merging**
